# Generated by Django 3.1.7 on 2021-05-03 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=240),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(max_length=240),
        ),
    ]
